#!/usr/bin/env python3
"""Rebuild the class site from the app build sources.

  python3 tools/build_site.py            # copy current builds into the site
  python3 tools/build_site.py --rebuild  # run both app builds first

Adds the site-only parts to each app: PWA tags, config.js + sync.js (optional
cloud accounts), and service worker registration. Also writes meta.js, which the
teacher dashboard uses for level, badge, and test names.
"""
import json, re, subprocess, sys, os
SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUEST_DIR = '/workspace/quest'
LAB_DIR = '/workspace/ic3-practice-app/build'
QUEST_OUT = '/workspace/ic3-computing-fundamentals/fun-course/IC3_Computing_Fundamentals_Quest.html'
LAB_OUT = '/workspace/ic3-practice-app/IC3_CF_Practice_Tests.html'

if '--rebuild' in sys.argv:
    subprocess.run([sys.executable, 'build_quest.py'], cwd=QUEST_DIR, check=True)
    subprocess.run([sys.executable, 'build_app.py'], cwd=LAB_DIR, check=True)

SW = ('<script>if("serviceWorker" in navigator&&location.protocol.indexOf("http")===0)'
      '{addEventListener("load",function(){navigator.serviceWorker.register("sw.js").catch(function(){})})}</script>')
SYNC = '<script src="config.js"></script><script src="sync.js"></script>'

def head(name, theme):
    return (f'<link rel="manifest" href="{name}.webmanifest"><meta name="theme-color" content="{theme}">'
            f'<link rel="icon" href="icons/{name}-192.png"><link rel="apple-touch-icon" href="icons/{name}-180.png">'
            f'<meta name="apple-mobile-web-app-capable" content="yes">\n{SYNC}\n')

def site_page(src, name, theme):
    html = open(src, encoding='utf-8').read()
    m = re.search(r'</title>\n', html)
    assert m, 'no </title>'
    html = html[:m.end()] + head(name, theme) + html[m.end():]
    assert html.rstrip().endswith('</body></html>')
    html = html.rstrip()[:-len('</body></html>')] + SW + '</body></html>\n'
    open(os.path.join(SITE, name + '.html'), 'w', encoding='utf-8').write(html)
    return html

def data_of(html):
    m = re.search(r'<script type="application/json" id="data">(.*?)</script>', html, re.S)
    return json.loads(m.group(1).replace('<\\/', '</'))

q = site_page(QUEST_OUT, 'quest', '#0f1530')
p = site_page(LAB_OUT, 'practice', '#0f7c83')
QD, PD = data_of(q), data_of(p)
tpl = open(os.path.join(QUEST_DIR, 'template.html'), encoding='utf-8').read()
ranks = json.loads(re.search(r"const RANKS=(\[.*?\]);", tpl).group(1).replace("'", '"'))
extra = [{'id': i, 'icon': c, 'name': n} for i, c, n in re.findall(r"\{id:'(\w+)',icon:'([^']+)',name:'([^']+)'", tpl)]
meta = dict(
    ranks=ranks,
    levels=[dict(id=L['id'], name=L['name'], icon=L['icon']) for L in QD['levels']],
    badges=[dict(id='lvl_' + L['id'], icon=L['icon'], name=L['name'] + ' Champ') for L in QD['levels']] + extra,
    tests=[dict(id=t['id'], name=t['name'], kind=t['kind'], program=t['program'], short=t.get('short', t['id'])) for t in PD['tests']]
          + [dict(id='final', name='Final Exam Review', kind='final', program='Final', short='FINAL')],
    domains=PD['domains'],
)
open(os.path.join(SITE, 'meta.js'), 'w', encoding='utf-8').write(
    '// Generated by tools/build_site.py. Names used by the teacher dashboard.\nwindow.JC_META=' +
    json.dumps(meta, ensure_ascii=False, separators=(',', ':')) + ';\n')
print('quest.html', len(q) // 1024, 'KB; practice.html', len(p) // 1024, 'KB; meta.js tests', len(meta['tests']), 'badges', len(meta['badges']))
